# See https://docs.olivetin.app/multi-inst.html for explanation about those ports

# Single frontend point
listenAddressSingleHTTPFrontend: 127.0.0.1:__PORT__
# REST Actions port
listenAddressRestActions: localhost:__PORT_REST__
# gRPC Actions port
listenAddressGrpcActions: localhost:__PORT_GRPC__
# WebUI Port
listenAddressWebUI: localhost:__PORT_WEBUI__

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

showNavigation: false

# When editing actions requiring *sudo*, don't forget to edit /etc/sudoers.d/__APP__ !

# Actions (buttons) to show up on the WebUI:
actions:

- title: Restart nginx
  icon: '<img width="80px" src="https://nginx.org/nginx.png">'
  shell: sudo systemctl restart nginx

- title: Restart YunoHost API
  icon: '<img width="80px" src="https://raw.githubusercontent.com/YunoHost/yunohost-artwork/main/logos/svg/yunohost-logo_black.svg">'
  shell: sudo systemctl restart yunohost-api

- title: Restart Jellyfin
  icon: '<img width="80px" src="https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg">'
  shell: sudo systemctl restart jellyfin

- title: Restart IHateMoney
  icon: '<img width="80px" src="https://raw.githubusercontent.com/YunoHost/apps/master/logos/ihatemoney.png">'
  shell: sudo systemctl restart ihatemoney
